logging:
  level:
    root: warn
    kr.jdj.api: debug

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exam?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&&allowMultiQueries=true&useSSL=false
    username: jdj
    password: jdj
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  url:
    base: http://localhost:8080
